### PR TITLE
Enhanced Navbar and Made it responsive

### PR DESCRIPTION
**Pull request by ishita2704**
I enhanced  the navbar added the home,blog ,about links and also made a hover effect over it .Kindly check and merge it .

### CODE REVIEW

**Comment by ishita2704** [comment]
ACM-JEC club - Google Chrome 20-10-2024 14_21_02

**Comment by chetankhandait** [comment]
Edit : Add a dashboard button instead of blog  and keep the profile drop-down in the navbar

**Comment by ishita2704** [comment]
ACM-JEC club - Google Chrome 20-10-2024 14_21_02
like this ?

**Comment by ishita2704** [comment]
ACM-JEC club - Google Chrome 20-10-2024 14_37_43
like this?

**Comment by chetankhandait** [comment]
> ACM-JEC club - Google Chrome 20-10-2024 14_37_43 like this?

Yess 👍

**Pull request merged**
